"""
Database Operations Package
Contains all database CRUD operations for the Telegram file distribution system.
"""

# Files operations
from .files import (
    add_file,
    get_file_by_post_no,
    get_file_by_id,
    get_all_files,
    update_file,
    delete_file,
    increment_download_count,
    get_total_files_count,
    get_total_downloads_count,
    get_most_downloaded_files,
    get_recent_files,
    get_files_by_admin,
    search_files,
    get_files_stats,
    file_exists,
    bulk_delete_files,
)

# Users operations
from .users import (
    get_user_by_id,
    create_user,
    update_user,
    get_all_users,
    get_all_users_count,
    get_verified_users,
    get_verified_users_count,
    get_active_users,
    get_users_joined_today,
    get_users_joined_this_week,
    get_users_joined_this_month,
    verify_user_manually,
    unverify_user,
    reset_user_file_limit,
    update_user_verification,
    increment_user_file_access,
    user_has_accessed_file,
    is_user_verified,
    cleanup_expired_verifications,
    get_user_stats,
    search_users,
    delete_user,
)

# Verification operations
from .verification import (
    create_verification_token,
    get_verification_token,
    get_token_by_user,
    update_token_status,
    delete_verification_token,
    is_token_valid,
    is_token_expired,
    mark_token_in_progress,
    mark_token_completed,
    mark_token_expired,
    cleanup_expired_tokens,
    get_pending_tokens,
    get_tokens_by_status,
    get_user_token_history,
    get_verification_stats,
    has_user_pending_token,
    invalidate_user_tokens,
    get_token_age_seconds,
    delete_user_tokens,
)

# Channels operations
from .channels import (
    add_channel,
    get_channel_by_id,
    get_channel_by_username,
    get_all_channels,
    get_active_channels,
    update_channel,
    remove_channel,
    toggle_channel_status,
    reorder_channels,
    get_channels_count,
    get_active_channels_count,
    channel_exists,
    bulk_update_channel_status,
    delete_all_inactive_channels,
)

# Settings operations
from .settings import (
    get_setting,
    get_setting_value,
    set_setting,
    get_all_settings,
    get_all_settings_dict,
    delete_setting,
    update_setting,
    setting_exists,
    get_settings_count,
    bulk_set_settings,
    get_settings_by_prefix,
    search_settings,
    get_settings_updated_since,
    get_settings_updated_by_admin,
    reset_setting_to_default,
    export_settings,
    import_settings,
    get_setting_history,
)

# Logs operations
from .logs import (
    log_admin_action,
    get_admin_logs,
    get_logs_by_admin,
    get_logs_by_action,
    get_recent_logs,
    get_logs_by_date_range,
    get_logs_count,
    get_admin_activity_stats,
    get_action_statistics,
    cleanup_old_logs,
    search_logs,
    delete_logs_by_admin,
    get_most_active_admins,
    get_log_by_id,
)

__all__ = [
    # Files
    'add_file',
    'get_file_by_post_no',
    'get_file_by_id',
    'get_all_files',
    'update_file',
    'delete_file',
    'increment_download_count',
    'get_total_files_count',
    'get_total_downloads_count',
    'get_most_downloaded_files',
    'get_recent_files',
    'get_files_by_admin',
    'search_files',
    'get_files_stats',
    'file_exists',
    'bulk_delete_files',
    
    # Users
    'get_user_by_id',
    'create_user',
    'update_user',
    'get_all_users',
    'get_all_users_count',
    'get_verified_users',
    'get_verified_users_count',
    'get_active_users',
    'get_users_joined_today',
    'get_users_joined_this_week',
    'get_users_joined_this_month',
    'verify_user_manually',
    'unverify_user',
    'reset_user_file_limit',
    'update_user_verification',
    'increment_user_file_access',
    'user_has_accessed_file',
    'is_user_verified',
    'cleanup_expired_verifications',
    'get_user_stats',
    'search_users',
    'delete_user',
    
    # Verification
    'create_verification_token',
    'get_verification_token',
    'get_token_by_user',
    'update_token_status',
    'delete_verification_token',
    'is_token_valid',
    'is_token_expired',
    'mark_token_in_progress',
    'mark_token_completed',
    'mark_token_expired',
    'cleanup_expired_tokens',
    'get_pending_tokens',
    'get_tokens_by_status',
    'get_user_token_history',
    'get_verification_stats',
    'has_user_pending_token',
    'invalidate_user_tokens',
    'get_token_age_seconds',
    'delete_user_tokens',
    
    # Channels
    'add_channel',
    'get_channel_by_id',
    'get_channel_by_username',
    'get_all_channels',
    'get_active_channels',
    'update_channel',
    'remove_channel',
    'toggle_channel_status',
    'reorder_channels',
    'get_channels_count',
    'get_active_channels_count',
    'channel_exists',
    'bulk_update_channel_status',
    'delete_all_inactive_channels',
    
    # Settings
    'get_setting',
    'get_setting_value',
    'set_setting',
    'get_all_settings',
    'get_all_settings_dict',
    'delete_setting',
    'update_setting',
    'setting_exists',
    'get_settings_count',
    'bulk_set_settings',
    'get_settings_by_prefix',
    'search_settings',
    'get_settings_updated_since',
    'get_settings_updated_by_admin',
    'reset_setting_to_default',
    'export_settings',
    'import_settings',
    'get_setting_history',
    
    # Logs
    'log_admin_action',
    'get_admin_logs',
    'get_logs_by_admin',
    'get_logs_by_action',
    'get_recent_logs',
    'get_logs_by_date_range',
    'get_logs_count',
    'get_admin_activity_stats',
    'get_action_statistics',
    'cleanup_old_logs',
    'search_logs',
    'delete_logs_by_admin',
    'get_most_active_admins',
    'get_log_by_id',
]